apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp
  template:
    metadata:
      labels:
        app: tcp
    spec:
      containers:
      - name: tcp
        image: hweicdl/netcat-tcp:v0.1.0
        ports:
        - containerPort: 4000
