apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sharedlbs.kubecon.k8s.io
spec:
  group: kubecon.k8s.io
  names:
    kind: SharedLB
    plural: sharedlbs
    shortNames:
    - slb
  additionalPrinterColumns:
  - name: External-IP
    type: string
    # TODO(Huang-Wei): verify how it prints for EKS which uses hostname
    JSONPath: .status.loadBalancer.ingress[*].*
  - name: Port
    type: string
    JSONPath: .spec.ports[*].port
  # can't combine protocol info along with "Port" column until
  # https://github.com/kubernetes/kubernetes/issues/67268 gets implemented
  - name: Protocol
    type: string
    JSONPath: .spec.ports[*].protocol
  - name: Ref
    type: string
    JSONPath: .status.ref
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            loadBalancerIP:
              type: string
            ports:
              items:
                type: object
              type: array
            selector:
              type: object
          type: object
        status:
          properties:
            loadBalancer:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
