apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp2
  template:
    metadata:
      labels:
        app: tcp2
    spec:
      containers:
      - name: tcp2
        image: hweicdl/netcat-tcp:v0.1.0
        ports:
        - containerPort: 4000
